Did some clean up.

diff --git a/src/shell/shell_functions b/src/shell/shell_functions
--- a/src/shell/shell_functions
+++ b/src/shell/shell_functions
@@ -4,81 +4,66 @@
 ## Path Short Hand(s) ##
  ######################
 # Shell root.
-echo "## shell_functions: ##"
-echo "\$0: '$0'"
-zero=$0
-echo "############"
-echo "readlink -f $0:"
-tmp="$(readlink -f $zero)"
-echo $tmp
-echo "readlink -f \"$0\":"
-tmp="$(readlink -f "$zero")"
-echo $tmp
-echo "readlink -f '$0':"
-tmp=$(readlink -f '$zero')
-echo $tmp
-echo "############"
-readlink -f $0
-echo "############"
-readlink -f '$0'
-echo "############"
-readlink -f "$0"
-echo "############"
 
 local pathToZero=$(readlink -f $0)
 echo "\$pathToZero: '$pathToZero'"
 
+# Get shell script root for users running this in there local environment.
 if [[ -d "$HOME/shell" ]]; then
 	declare -x SHELL_ROOT=$HOME/shell
-# Attempt to find root using $0.
-elif [[ -d "$pathToZero/shell" ]]; then
-	export SHELL_ROOT=$pathToZero/shell
-elif [[ -d "$pathToZero/src/shell" ]]; then
-	export SHELL_ROOT=$pathToZero/src/shell
-elif [[ -d "$pathToZero/../shell" ]]; then
-	export SHELL_ROOT=$pathToZero/../shell
-elif [[ -d "$pathToZero/../src/shell" ]]; then
-	export SHELL_ROOT=$pathToZero/../src/shell
-elif [[ -d "$pathToZero/../../shell" ]]; then
-	export SHELL_ROOT=$pathToZero/../../shell
-elif [[ -d "$pathToZero/../../src/shell" ]]; then
-	export SHELL_ROOT=$pathToZero/../../src/shell
-elif [[ -d "$pathToZero/../../../shell" ]]; then
-	export SHELL_ROOT=$pathToZero/../../../shell
-elif [[ -d "$pathToZero/../../../src/shell" ]]; then
-	export SHELL_ROOT=$pathToZero/../../../src/shell
-elif [[ -d "$pathToZero/../../../../shell" ]]; then
-	export SHELL_ROOT=$pathToZero/../../../../shell
-elif [[ -d "$pathToZero/../../../../src/shell" ]]; then
-	export SHELL_ROOT=$pathToZero/../../../../src/shell
-# Attempt to find root using $PWD.
-elif [[ -d "$PWD/shell" ]]; then
-	export SHELL_ROOT=$PWD/shell
-elif [[ -d "$PWD/src/shell" ]]; then
-	export SHELL_ROOT=$PWD/src/shell
-elif [[ -d "$PWD/../shell" ]]; then
-	export SHELL_ROOT=$PWD/../shell
-elif [[ -d "$PWD/../src/shell" ]]; then
-	export SHELL_ROOT=$PWD/../src/shell
-elif [[ -d "$PWD/../../shell" ]]; then
-	export SHELL_ROOT=$PWD/../../shell
-elif [[ -d "$PWD/../../src/shell" ]]; then
-	export SHELL_ROOT=$PWD/../../src/shell
-elif [[ -d "$PWD/../../../shell" ]]; then
-	export SHELL_ROOT=$PWD/../../../shell
-elif [[ -d "$PWD/../../../src/shell" ]]; then
-	export SHELL_ROOT=$PWD/../../../src/shell
-elif [[ -d "$PWD/../../../../shell" ]]; then
-	export SHELL_ROOT=$PWD/../../../../shell
-elif [[ -d "$PWD/../../../../src/shell" ]]; then
-	export SHELL_ROOT=$PWD/../../../../src/shell
+# Attempt to find shell script root when run from CI/CD runner or any other time that this isn't be sourced to setup
+# a user's environment.
 else
-	echo "ERROR, couldn't find root of shell scripts."
-	exit 1
+	# Attempt to find root using $0.
+	elif [[ -d "$pathToZero/shell" ]]; then
+		export SHELL_ROOT=$pathToZero/shell
+	elif [[ -d "$pathToZero/src/shell" ]]; then
+		export SHELL_ROOT=$pathToZero/src/shell
+	elif [[ -d "$pathToZero/../shell" ]]; then
+		export SHELL_ROOT=$(readlink -f $pathToZero/../shell)
+	elif [[ -d "$pathToZero/../src/shell" ]]; then
+		export SHELL_ROOT=$(readlink -f $pathToZero/../src/shell)
+	elif [[ -d "$pathToZero/../../shell" ]]; then
+		export SHELL_ROOT=$(readlink -f $pathToZero/../../shell)
+	elif [[ -d "$pathToZero/../../src/shell" ]]; then
+		export SHELL_ROOT=$(readlink -f $pathToZero/../../src/shell)
+	elif [[ -d "$pathToZero/../../../shell" ]]; then
+		export SHELL_ROOT=$(readlink -f $pathToZero/../../../shell)
+	elif [[ -d "$pathToZero/../../../src/shell" ]]; then
+		export SHELL_ROOT=$(readlink -f $pathToZero/../../../src/shell)
+	elif [[ -d "$pathToZero/../../../../shell" ]]; then
+		export SHELL_ROOT=$(readlink -f $pathToZero/../../../../shell)
+	elif [[ -d "$pathToZero/../../../../src/shell" ]]; then
+		export SHELL_ROOT=$(readlink -f $pathToZero/../../../../src/shell)
+	# Attempt to find root using $PWD.
+	elif [[ -d "$PWD/shell" ]]; then
+		export SHELL_ROOT=$PWD/shell
+	elif [[ -d "$PWD/src/shell" ]]; then
+		export SHELL_ROOT=$PWD/src/shell
+	elif [[ -d "$PWD/../shell" ]]; then
+		export SHELL_ROOT=$(readlink -f $PWD/../shell)
+	elif [[ -d "$PWD/../src/shell" ]]; then
+		export SHELL_ROOT=$(readlink -f $PWD/../src/shell)
+	elif [[ -d "$PWD/../../shell" ]]; then
+		export SHELL_ROOT=$(readlink -f $PWD/../../shell)
+	elif [[ -d "$PWD/../../src/shell" ]]; then
+		export SHELL_ROOT=$(readlink -f $PWD/../../src/shell)
+	elif [[ -d "$PWD/../../../shell" ]]; then
+		export SHELL_ROOT=$(readlink -f $PWD/../../../shell)
+	elif [[ -d "$PWD/../../../src/shell" ]]; then
+		export SHELL_ROOT=$(readlink -f $PWD/../../../src/shell)
+	elif [[ -d "$PWD/../../../../shell" ]]; then
+		export SHELL_ROOT=$(readlink -f $PWD/../../../../shell)
+	elif [[ -d "$PWD/../../../../src/shell" ]]; then
+		export SHELL_ROOT=$(readlink -f $PWD/../../../../src/shell)
+	else
+		echo "ERROR, couldn't find root of shell scripts."
+		exit 1
+	fi
 fi
 echo "\$SHELL_ROOT: '$SHELL_ROOT'"
-cmdOut=$(readlink -f $SHELL_ROOT)
-echo "\$(readlink -f $SHELL_ROOT): '$cmdOut'"
+#cmdOut=$(readlink -f $SHELL_ROOT)
+#echo "\$(readlink -f $SHELL_ROOT): '$cmdOut'"
 # Shell function(s) root.
 declare -x SHELL_FUNCTIONS=$SHELL_ROOT/functions
 # Shell function's constant(s).
